# See https://developers.google.com/web/updates/2017/06/headless-karma-mocha-chai
language: node_js
node_js:
  - "12"
sudo: required
os:
#- windows
- linux
- osx
addons:
  chrome: stable # have Travis install chrome stable.
  sonarcloud:
    organization: acrolinx
script:
  - npm run build
