language: node_js
node_js:
- '12'
sudo: required
os:
- linux
addons:
  chrome: stable
  sonarcloud:
    organization: acrolinx
    token:
      secure: A/i3zcoQvXNqXuONZUBHrVx/VV0AQxfdNZrYBU4nV36kWDUxrzkTwtKeeLumfYWocekDhlnHpU+MUEyj9gjMmQps6As2GY+hPxF+UFQ3oPHoWAL3vuOLpZZxJOL3iOOkA8NN2IajNsedV+c+CjfnecLFU6hf0o1XC/JkKv0UhvH2Ot9+JZFJg2CZcceDuvLyvIGs6BhpQ7DQfKyLfVXNy7thCZcM9udPdb4sI63t6lP5Rxb5PgsAi7LL5rFbhXLeev3uvaJTWHJSIprj85GINsGdFf0BLIaFwSxxgdR1I1Aw3Y5c/vELjFfv3qjwYjJTXEvgWrmGhb9kfxl3Cmtd5bfNRCLMIqh1K8R0L7e41s4iS51WaKmFL4DS423W6nrRnHtJHV0PKrW0P7sK5YTs+7PpXM6Gt8AwTwSonnWqHjiPUpFiPPFg7WvNvR/Q/WR7X0xQah+8sKWP1vrAq7KphRUHnICSkUnW0wD8F2SsuSVpo0RLKzgdvA+of2PC0Dqec+5KzlY5Kj7NjwkqTuHZiTzCg/cwdpDFvAH70l+YZz9h2/XfSOMVq4Zl1UB9XarCO/+4zmRtGakOpMPXsJrq7/NNjfMB9oPa6F4OKJMFZuUX+SLpzAwjKu9vw9yzj0Foql4LguzAdNyYaB4UP+2FxFqb768haexmpppsfGq7aPs=
script:
- npm run build
- npm run buildDoc
- sonar-scanner
# Check for suitable licenses
- export v=`node -p "require('./package.json').version"`
- export n=`node -p "require('./package.json').name"`
- npx license-checker --production --onlyAllow 'BSD;CC-PDDC;CC-BY-3.0;CC-BY-1.0;CC-BY-2.0;CC-BY-4.0;CC0-1.0;Apache;Artistic;MIT;MPL;ISC;Unlicense' --excludePackages "$n@$v$LICENSE_EXCLUDED_PACKAGES" --excludePrivatePackages

deploy:
- provider: pages
  skip-cleanup: true
  github-token: $GITHUB_API_TOKEN
  keep-history: true
  local-dir: "./docs/"
  on:
    tags: true
env:
  global:
    secure: VDAZjvIWALT97uj0ReSKmyRTx++Ph7ZeTNANg0HDfiwPcfjZbuzAZaW0b9GbVq8Z9r2elTUd5b3qDH02K7lgeKqSdwgF3lelvjdT4upf2MgAYmGBCYamCOHSi5tD/aPTRNnsfeQu4HcTyKWayJEQtomFqoDF9s6qW6tepFhjbygYZS7TY0ep2g8edouJu6jxB/MduDdIDWgumpfRQNfNpr7VQ5Ws0fVs+fLyiNGlSs3yz4vNyBtnDY6+FGVXPDnXkeF7FM5mgmLoEcWTkX6hhk0Fq2Ml4vKoyB4zZVq6DTsG1K93ht4ywMLikXiqyjw1xvv2r6M8n75lrlzMJllYMUpJrhtu20FyvX+BqwQmsa4F4505bi9sX3xP4wWbcdi0UL+JTuElIyL1Bp1TTOq6G1wcuVISjsCmW1A7K4qko/JO1JiwV33fInVa/S0eGYP3QZGlcp/4qyQg6HE8EyU2K91SQaglsIAtd+u817BTCeGrfgtcLFD0MHlRQr6eT+A+Alesx1JWnu+cqUNGBnKNCOaP+Dwk4IQTjpy8vxd5Vo6kY87dQJGxr1K6LcZ+imytM3y1K7r31F1JBEQ12mronv0St+7Hen3ZXl5kiTmY5mdU/womZEpF9U1tcY4H0fU5o7Byz6V2zvD0OZNQg685dwVCwxiEHIFrI17usycotW0=
