name: Build

on:
  push:
  pull_request:
  schedule:
    - cron: '0 3 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Setup SonarCloud Scan
        uses: sonarsource/sonarqube-scan-action@v5
        with:
          args: -Dsonar.organization=acrolinx
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONARCLOUD_TOKEN }}

      - name: Run build
        run: |
          npm ci
          npm run lint
          npm run build
          npm run build-doc
          npm run coverage
