name: GitHub Actions sidebar-sdk-js
on: [push]
jobs:
  GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup Nodejs
        uses: actions/setup-node@v2
        with:
          node-version: '12' 
          
      - name: Setup SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@master
        with:
          args: >
            -Dsonar.organization=acrolinx
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: A/i3zcoQvXNqXuONZUBHrVx/VV0AQxfdNZrYBU4nV36kWDUxrzkTwtKeeLumfYWocekDhlnHpU+MUEyj9gjMmQps6As2GY+hPxF+UFQ3oPHoWAL3vuOLpZZxJOL3iOOkA8NN2IajNsedV+c+CjfnecLFU6hf0o1XC/JkKv0UhvH2Ot9+JZFJg2CZcceDuvLyvIGs6BhpQ7DQfKyLfVXNy7thCZcM9udPdb4sI63t6lP5Rxb5PgsAi7LL5rFbhXLeev3uvaJTWHJSIprj85GINsGdFf0BLIaFwSxxgdR1I1Aw3Y5c/vELjFfv3qjwYjJTXEvgWrmGhb9kfxl3Cmtd5bfNRCLMIqh1K8R0L7e41s4iS51WaKmFL4DS423W6nrRnHtJHV0PKrW0P7sK5YTs+7PpXM6Gt8AwTwSonnWqHjiPUpFiPPFg7WvNvR/Q/WR7X0xQah+8sKWP1vrAq7KphRUHnICSkUnW0wD8F2SsuSVpo0RLKzgdvA+of2PC0Dqec+5KzlY5Kj7NjwkqTuHZiTzCg/cwdpDFvAH70l+YZz9h2/XfSOMVq4Zl1UB9XarCO/+4zmRtGakOpMPXsJrq7/NNjfMB9oPa6F4OKJMFZuUX+SLpzAwjKu9vw9yzj0Foql4LguzAdNyYaB4UP+2FxFqb768haexmpppsfGq7aPs=  

      - name: Setup and Audit Source Code    
        run: |
          npm ci
          npm audit --production --audit-level=moderate   
          
      - name: Check for suitable licenses
        run: |
         export v=`node -p "require('./package.json').version"`
         export n=`node -p "require('./package.json').name"`
         npx license-checker --production --onlyAllow 'BSD;CC-PDDC;CC-BY-3.0;CC-BY-1.0;CC-BY-2.0;CC-BY-4.0;CC0-1.0;Apache;Artistic;MIT;MPL;ISC;Unlicense' --excludePackages "$n@$v$LICENSE_EXCLUDED_PACKAGES" --excludePrivatePackages
         
      - name: Build
        run: |
          npm run build
          npm run buildDoc
      - name: Scan with SonarCloud Scan  
        run: sonar-scanner
